version: 'build-{build}-{branch}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

before_build:
  - cmake -G "Visual Studio 15 2017" -A x64 .

build:
  project: $(APPVEYOR_PROJECT_NAME).sln
