version: 'build-{build}-{branch}'

image:
  - Visual Studio 2017
  - Ubuntu1804

platform:
  - x64

configuration:
  - Release

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

for:
-
  matrix:
    only:
      - image: Ubuntu1804

  cache:
    - ~/.conan -> conanfile.txt

  install:
    # Install clang 7
    - sudo apt-get -qq update
    - sudo apt-get install -y -q clang-7 clang++-7
    - export CC=clang-7 CXX=clang++-7
    # Doxygen and graphviz are required by the `doc` target
    - sudo apt-get install -y -q doxygen graphviz
    # Install Conan
    - sudo pip install --quiet conan
    - conan user

  before_build:
    - conan install . -s build_type=$CONFIGURATION --install-folder=build --build missing
    - mkdir -p build; cd build; cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ..

  build_script:
    - make -j3

  test_script:
    - ctest

-
  matrix:
    only:
      - image: Visual Studio 2017

  cache:
    - C:\Users\Appveyor\choco-cache -> .appveyor.yml
    - C:\Users\Appveyor\.conan -> conanfile.txt
    - C:\.conan -> conanfile.txt

  install:
    # Change where Chocolatey caches downloads
    - choco config set cacheLocation C:\Users\Appveyor\choco-cache
    # Doxygen and graphviz are required by the `doc` target
    - choco upgrade --no-progress doxygen.install graphviz
    # Update CMake to fix compatibility issue with Doxygen
    - choco upgrade --no-progress cmake.install --installargs 'ADD_CMAKE_TO_PATH=System'
    - refreshenv
    # Install Conan
    - pip install --quiet conan
    - conan user

  before_build:
    - conan install . -s build_type=%CONFIGURATION% --build missing
    - cmake -G "Visual Studio 15 2017" -A x64 .

  build_script:
    - msbuild %APPVEYOR_PROJECT_NAME%.sln /m  /p:BuildInParallel="True" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  test_script:
    - ctest -C %CONFIGURATION%
