version: 'build-{build}-{branch}'

image:
  - Visual Studio 2019
  - Ubuntu1804

platform:
  - x64

configuration:
  - Release

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

for:
-
  matrix:
    only:
      - image: Ubuntu1804

  cache:
    - /home/appveyor/.conan -> conanfile.txt
    - /home/appveyor/.cache/pip -> .appveyor.yml

  install:
    # Enable `--no-install-recommends` by default
    - apt-config dump | grep -we Recommends -e Suggests | sed s/1/0/ | sudo tee /etc/apt/apt.conf.d/999norecommend

    # Install clang 8
    - wget -q -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
    - sudo apt-get -qq update
    - sudo apt-get install -y -q clang-8 clang++-8
    - export CC=clang-8 CXX=clang++-8

    - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 100
    - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-8 100
    - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-8 100
    - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-8 100

    # Doxygen and graphviz are required by the `doc` target
    - sudo apt-get install -y -q doxygen graphviz

    # Install Conan
    - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q python3 python3-pip python3-setuptools python3-wheel
    - sudo -H pip3 install conan
    - conan user

  before_build:
    - conan install . -s build_type=$CONFIGURATION --install-folder=build --build missing
    - mkdir -p build; cd build; cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ..

  build_script:
    - make -j3

  test_script:
    - ctest

-
  matrix:
    only:
      - image: Visual Studio 2019

  cache:
    - C:\Users\Appveyor\choco-cache -> .appveyor.yml
    - C:\Users\Appveyor\.conan -> conanfile.txt
    - C:\Users\Appveyor\AppData\Local\pip\Cache -> .appveyor.yml

  install:
    # Change where Chocolatey caches downloads
    - choco config set cacheLocation C:\Users\Appveyor\choco-cache
    # Doxygen and graphviz are required by the `doc` target
    - choco upgrade --no-progress doxygen.install graphviz
    # Install Conan
    - pip install conan
    - conan user

  before_build:
    - conan install . -s build_type=%CONFIGURATION% --build missing
    - cmake -G "Visual Studio 16 2019" -A x64 .

  build_script:
    - msbuild %APPVEYOR_PROJECT_NAME%.sln /m  /p:BuildInParallel="True" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  test_script:
    - ctest -C %CONFIGURATION%
