version: 'build-{build}-{branch}'

image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  # Install clang on Ubuntu
  - sh: |
        sudo apt-get -qq update
        sudo apt-get install -y -q clang-6.0 clang++-6.0
  - sh: export CC=clang-6.0 CXX=clang++-6.0
  # Install Catch2 dependency, will try to replace with a Conan package later
  - ps: .\install-catch2.ps1
  - sh: ./install-catch2.sh

for:
-
  matrix:
    only:
      - image: Ubuntu

  before_build:
    - mkdir -p build; cd build; cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..

  build_script:
    - make

-
  matrix:
    only:
      - image: Visual Studio 2017

  before_build:
    - cmake -G "Visual Studio 15 2017" -A x64 .

  build_script:
    - msbuild %APPVEYOR_PROJECT_NAME%.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - ctest -C %CONFIGURATION%
