os: linux
dist: focal

language: cpp

jobs:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - doxygen
            - graphviz
            - libperlio-gzip-perl
            - libjson-perl
            - ninja-build
            - python3
            - python3-pip
            - python3-setuptools
            - python3-wheel
      cache:
        directories:
          - ~/.conan
          - ~/.cache/pip
      before_install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 100

        # Install the latest lcov
        # The GCC intermediate format is not supported by lcov 1.14
        - pushd /tmp
        - git clone --branch master --depth 1 https://github.com/linux-test-project/lcov.git
        - cd lcov && sudo make install
        - popd

        # Install Conan
        - sudo -H pip3 install conan
      script:
        - mkdir -p build && cd build
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON ..
        - ninja
        - ctest
      after_success:
        # Upload report to CodeCov
        - bash <(curl -s https://codecov.io/bash) -f ccov/Tests.info || echo "Codecov did not collect coverage reports"

    - os: windows
      cache:
        directories:
          - $HOME\choco-cache
          - $HOME\.conan

      before_install:
        # Change where Chocolatey caches downloads
        - choco config set cacheLocation C:\Users\Travis\choco-cache

        # Doxygen and graphviz are required by the `doc` target
        - choco upgrade --no-progress doxygen.install graphviz

        # Use Python3
        - choco upgrade --no-progress python3
        - refreshenv

        # Install Conan
        - pip3 install conan

      script:
        - cmake -G "Visual Studio 16 2019" -A x64 .
        - msbuild CI-CD-Tests.sln /m  /p:BuildInParallel="True"

      test_script:
        - ctest -C Release

    - os: osx
      osx_image: xcode12
      compiler: clang
      addons:
        homebrew:
          update: true
          packages:
            - doxygen
            - graphviz
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1
      cache:
        directories:
          - ~/.conan
          - ~/Library/Caches/pip
      before_install:
        # Install Conan
        - pip3 install conan
      script:
        - mkdir -p build && cd build
        - cmake -G Xcode ..
        - xcodebuild -project CI-CD-Tests.xcodeproj -configuration Release
        - ctest -C Release
      before_deploy:
        - xcodebuild -project CI-CD-Tests.xcodeproj -target doc
      deploy:
        provider: pages
        local_dir: html
        token: $GITHUB_TOKEN
        edge: true
