dist: trusty
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-7', 'g++-7', 'cmake']
      env: COMPILERS="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10
      compiler: clang
      env: COMPILERS='CC=clang && CXX=clang++'

before_install:
  - eval "${COMPILERS}"

script:
  - mkdir -p build && cd build
  - cmake ..
  - make
