dist: trusty
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-7', 'g++-7', 'cmake', 'doxygen', 'graphviz']
      env: COMPILERS="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10
      compiler: clang
      addons:
        homebrew:
          packages: ['doxygen', 'graphviz'] # These are required by CMake for the doc target
      env:
        - COMPILERS='CC=clang && CXX=clang++'
        - CMAKE_FLAGS="-G Xcode"

cache:
  directories:
    - /usr/local/include/
    - /usr/local/lib/
    - /usr/local/share/

before_install:
  # Install Catch2 dependency, will try to replace with a Conan package later
  - ./install-catch2.sh
  - eval "${COMPILERS}"

script:
  - mkdir -p build && cd build
  - cmake $CMAKE_FLAGS ..
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      xcodebuild -project CI-CD-Tests.xcodeproj -alltargets -configuration Release
    else
      make
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ctest -C Release
    else
      ctest
    fi

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build/html
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    condition: $TRAVIS_OS_NAME = osx
    branch: master
