dist: bionic
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - doxygen
            - graphviz
            - libperlio-gzip-perl
            - libjson-perl
            - python3
            - python3-pip
            - python3-setuptools
            - python3-wheel
      cache:
        directories:
          - ~/.conan
          - ~/.cache/pip
      before_install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 100

        # Install the latest lcov
        # The GCC intermediate format is not supported by lcov 1.14
        - pushd /tmp
        - git clone --branch master --depth 1 https://github.com/linux-test-project/lcov.git
        - cd lcov && sudo make install
        - popd

        # Install Conan
        - sudo -H pip3 install conan
        # Detect architecture and compiler
        - conan user
      script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON ..
        - make -j3
        - make ccov-Tests
        - ctest
      after_success:
        # Upload report to CodeCov
        - bash <(curl -s https://codecov.io/bash) -f ccov/Tests.info || echo "Codecov did not collect coverage reports"

    - os: osx
      osx_image: xcode11.3
      compiler: clang
      addons:
        homebrew:
          update: true
          packages:
            - doxygen
            - graphviz
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
      cache:
        directories:
          - ~/.conan
          - ~/Library/Caches/pip
      before_install:
        # Install Conan
        - pip3 install conan
        # Detect architecture and compiler
        - conan user
      script:
        - mkdir -p build && cd build
        - cmake -G Xcode ..
        - xcodebuild -project CI-CD-Tests.xcodeproj -configuration Release
        - ctest -C Release
      before_deploy:
        - xcodebuild -project CI-CD-Tests.xcodeproj -target doc
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: build/html
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master

install:
  # Download and build dependencies
  - conan install . -s build_type=Release --install-folder=build --build missing
